### ISSUE TITLE
Use a separate embed for waifu unlock rather than the reveal embed for /airrec

### ISSUE THREAD

**Issue by accadaccacool** [KingWaffleIII/plane#46]
Easter eggs remove the image after reveal which make it difficult for user to compare listed features with image. Perhaps separate message or disable option?

**Comment by KingWaffleIII** [comment]
Thank you for your issue. After deliberating, the 50% spawn rate of waifus was deemed way too high so that's being reduced. Furthermore, we will be implementing these Easter eggs as an actual feature of the bot. So, if a waifu spawn is successful (33% chance now), the reveal embed won't show a waifu anymore but the original aircraft and then it will follow up with a waifu unlock embed.

TL;DR this will be fixed in v1.3.0 "Super Galahad"

**Comment by KingWaffleIII** [comment]
Edited the name for verbosity and to help me.
